local frame_lifetime = 1

---@class SwordHitController
---@field frames integer

---@param self SwordHitController
function init(self)
    self.frames = 0
end

function update(self, _dt)
    self.frames = self.frames + 1

    if self.frames >= frame_lifetime then
        go.delete()
    end
end

function on_message(self, message_id, message, sender)
    msg.post(message.other_id, hash("take_damage"), { damage = go.get("/player#player_controller", "sword_damage") })
end
